### ISSUE TITLE
Удаленка

### ISSUE THREAD

**Issue by pingvi92** [dev-cdmm/iptv.smotreshka#1]
Можно ли сделать мод, чтобы можно было с хостинга хапрашивать, а не с локалхоста?
А то пока что с хостинга не работает, ибо обрабатывается айпишником хоста, а не клиента

**Comment by dev-cdmm** [comment]
Если IP хостинга в российском сегменте — должно все работать, при корректных данных авторизации.

Если не в российском, единственное что возможно, использовать ru прокси, так как я думаю Смотрешка не даст авторизоваться с не российского ip (из-за авторских прав на контент).

Нужно больше данных для решения проблемы — логи web сервера. Также необходимо проверить доступны ли на хостинге все необходимые версии php, curl, gzip.

В моей конфигурации, я использую веб-сервер nginx на локальной машине (Ubuntu Server) в сети со следующими php параметрами для данного хоста

`location ~ \.php$ {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`fastcgi_buffer_size 32k;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`fastcgi_buffers 4 32k;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`fastcgi_index index.php;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`include /etc/nginx/fastcgi.conf;`
`}`

**Comment by pingvi92** [comment]
Я проживаю в европе.
Сама смотрешка (через сайт или через приложение у меня работает и без прокси), даже данный скрипт на локахосте отрабатывает на 100% и все работает, а вот хостинг у меня российский и (как мне кажется) выдает мне токен, который привязан к России, отсюда и невозможность смотреть.

Если бы можно было как-то подсунуть во время обработки (я так понимаю, во время логина) реальный айпи (мой европейский, а не российский с хостинга, то все должно работать.

Вопрос лишь в том, как? в curl headers пробовал делать проброс айпи 
```
    $ip = $_SERVER["REMOTE_ADDR"];
    $headers = array();
    $headers[] = 'Connection: keep-alive';
    $headers[] = 'Cache-Control: no-cache';
    $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8';
    $headers[] = "REMOTE_ADDR: $ip";
    $headers[] = "X-Forwarded-For: $ip";
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
```

Но, увы, не вышло.
    
Может есть какие-то идеи?

**Comment by dev-cdmm** [comment]
Пробую воспроизвести проблему с таким же окружением.
А каков результат выполнения при запросе?  
Ошибка HTTP, пустой плейлист или плейлист с не воспроизводимыми данными?

**Comment by pingvi92** [comment]
> Ошибка HTTP, пустой плейлист или плейлист с не воспроизводимыми данными?

да, плейлист генерится, но не воспроизводится.

**Comment by dev-cdmm** [comment]
Изучил этот вопрос. Действительно Смотрешка генерирует token исходя из source ip. И никакие манипуляции с заголовками тут не помогают.

Здесь есть три решения, на мой взгляд:

1. Переписать php на js, и заменить curl на ajax в секции загрузки url канала с fe.smotreshka.tv/playback-info.
2. Поднять прокси на нужном ip, и пускать curl через него
3. Попытаться найти в API параметр, который отвечает за IP

Поэтому на данный момент простого готового решения этой проблемы нет.
Спасибо, что сообщили о подобном ограничении. 
Добавлю информацию об этом в README.
